 
 /* Criação da Base de Dados */ 
 CREATE DATABASE IF NOT EXISTS LIVRARIA;


USE LIVRARIA; 
 
 /* Criação da tabela */ 
 CREATE TABLE IF NOT EXISTS LIVROS(
	NOME_DO_LIVRO VARCHAR(30),
	NOME_DO_AUTOR VARCHAR(30),
	SEXO_DO_AUTOR ENUM('FEMININO', 'MASCULINO'),
	NUMERO_DE_PAGINAS INT,
	NOME_DA_EDITORA VARCHAR(30),
	VALOR_DO_LIVRO DOUBLE ,
	UF_DA_EDITORA CHAR(2),
	ANO_PUBLICACAO INT
 );
 
 select * from LIVROS;