show databases;

/* CRIANDO A BASE DE DADOS */
CREATE DATABASE EXEMPLO; /*COMTEM ERRO FALTA O ; */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */
USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES*/
CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);